### ISSUE TITLE
python-build definitions out of date

### ISSUE THREAD

**Issue by ysgard** [darwin67/chef-pyenv#12]
And there doesn't appear to be any mechanism to update them.

Latest versions provided by cookbook:
2.7.6
3.4.0

Latest versions of python:
2.7.13
3.6.2

chef-pyenv should download the latest list before running any python installs.

**Comment by darwin67** [comment]
Thank you for the comment.

I'm working on an update to change the default to get the latest version of pyenv.
But you can still change the default attributes in your own wrapper cookbook to install the appropriate versions.

https://github.com/darwin67/chef-pyenv/blob/master/attributes/default.rb#L2-L3

I'm going to close this since it's not really an issue.
